### ISSUE TITLE
Unable to read file

### ISSUE THREAD

**Issue by matclab** [Geemili/time-tracker#1]
I tried time-tracker, but it failed with
```
$ target/release/time-tracker                          
An error occured: Error reading data: Unable to read file /tmp/time-tracker/laptop.unknown: Unable to read timesheet from /tmp/time-tracker/laptop.unknown: No such file or directory (os error 2)
```
The config file is :
```
sync_folder = "/tmp/time-tracker/"                                                                        
device_id = "laptop"  
```

**Comment by ErichDonGubler** [comment]
I also was unable to get things to work easily. I resolved the issue by creating a totally empty file at the location indicated in the error. So, in your case, that'd be something like:

```
touch /tmp/time-tracker/laptop.unknown
```

Unfortunately, doing something like `echo '' >> /tmp/time-tracker/laptop.unknown` doesn't work, because the timesheet parser simply bails on the empty line that it creates.

**Comment by leroycep** [comment]
Ah, sorry, I didn't see this issue till just now. I'll look into fixing this when I get home.

**Comment by matclab** [comment]
Thanks ! I'll give another try…
